export default [
  {
    title: '即時資訊',
    icon: 'ActivityIcon',
    children: [
      {
        title: '儀錶板',
        route: 'home',
        action: 'read',
        resource: 'Dashboard',
      },
      {
        title: '即時數據',
        route: 'realtime-data',
        action: 'read',
        resource: 'Dashboard',
      },
      {
        title: '即時AQI',
        route: 'realtime-aqi',
        action: 'read',
        resource: 'Dashboard',
      },
    ],
  },
  {
    title: '數據查詢',
    icon: 'DatabaseIcon',
    children: [
      {
        title: '歷史資料查詢',
        route: 'history-data',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '歷史趨勢圖',
        route: 'history-trend',
        action: 'read',
        resource: 'Data',
      },
      {
        title: 'AQI趨勢圖',
        route: 'aqi-trend',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '雙測項對比圖',
        route: 'scatter-chart',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '煙流回推軌跡線',
        route: 'trace-query',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '玫瑰圖查詢',
        route: 'wind-rose-query',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '校正資料查詢',
        route: 'calibration-query',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '多點校正查詢',
        route: 'multi-calibration-query',
        action: 'read',
        resource: 'Data',
      },
      {
        title: '警報記錄查詢',
        route: 'alarm-query',
        action: 'read',
        resource: 'Data',
      },
    ],
  },
  {
    title: '報表查詢',
    icon: 'BookOpenIcon',
    action: 'read',
    resource: 'Report',
    children: [
      {
        title: '監測報表',
        route: 'report',
        action: 'read',
        resource: 'Report',
      },
      {
        title: '月份時報表',
        route: 'monthly-hour-report',
        action: 'read',
        resource: 'Report',
      },
    ],
  },
  {
    title: '維護操作',
    icon: 'ActivityIcon',
    route: 'instrument-maintenance',
    action: 'set',
    resource: 'Maintenance',
  },
  {
    title: '系統管理',
    icon: 'SettingsIcon',
    action: 'set',
    resource: 'SystemSettings',
    children: [
      {
        title: '儀器管理',
        route: 'instrument-management',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '儀器狀態查詢',
        route: 'instrument-status',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '測點管理',
        route: 'monitor-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '測項管理',
        route: 'monitor-type-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '測項群組管理',
        route: 'monitor-type-group',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '狀態碼管理',
        route: 'monitor-status-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '多點校正管理',
        route: 'calibration-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '警報規則管理',
        route: 'alarm-rule-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '數位訊號管理',
        route: 'signal-type-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '人工資料註記',
        route: 'manual-audit',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '人工註記查詢',
        route: 'audit-log-query',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '使用者管理',
        route: 'user-management',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '群組管理',
        route: 'group-management',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '資料檢核設定',
        route: 'audit-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '資料上傳',
        route: 'data-management',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: 'CDX上傳設定',
        route: 'cdx-upload-config',
        action: 'set',
        resource: 'SystemSettings',
      },
      {
        title: '參數設定',
        route: 'system-config',
        action: 'set',
        resource: 'SystemSettings',
      },
    ],
  },
]
