#MODBUS Floating Point Input Registers
ID="CEMS"
description="CEMS 分析儀"

protocol=["serial", "tcp"]
# multiplier=1.0

#check DataType 8
byteSwapMode=9
byteSwapMode64=15

# ["測項代碼", 位址]
Data: [  
  ["NOX", 2000]
  ["SO2", 2002]
  ["TEMP", 2004]
  ["O2", 2006]
  ["PRESS", 2008]
  ["PM", 2010]
  ["FLOW", 2012]
  ["CO", 2014]  
]
# zero address, span address
Calibration: []

#(32-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input {
  reg: [
  ]
}
#(64-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input64 {
  reg: [
  ]
}
#(32-bit IEEE 754 format; read/write in high-word, low-word order; read/write)
Holding {
  reg: [       
    [2000, "NOx", "mg/Nm3"]
	[2002, "SO2", "mg/Nm3"]        
	[2004, "Temperature", "C"]
	[2006, "O2", "%"]
	[2008, "Pressure", "mBar"]
	[2010, "PM", "mg/Nm3"]
	[2012, "Flow", "m3/h"]
	[2014, "CO", "mg/Nm3"]	
  ]
}

Holding64 {
  reg: [  	
  ]
}

#Discrete Input Registers (only keep warning)
#(single-bit; read-only)
DiscreteInput {
  mode: []
  warning: []
}
#Coil Registers
#(single-bit; read/write)
Coil {
  reg: []
}
