#MODBUS Floating Point Input Registers
ID = "CWMS_TF"
description = "CWMS 分析儀 TF"

protocol = ["serial", "tcp"]
# multiplier=1.0

#check DataType 8
byteSwapMode = 9
byteSwapMode64 = 15

# ["測項代碼", 位址]
Data: [  
  ["TOTAL_FLOW_OUT", 2016]
]
# zero address, span address
Calibration: []

#(32-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input {
  reg: [
  ]
}
#(64-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input64 {
  reg: [
  ]
}
#(32-bit IEEE 754 format; read/write in high-word, low-word order; read/write)
Holding {
  reg: [    
  ]
}

Holding64 {
  reg: [
    [2016, "Total Flow Out", "m3"]
  ]
}

#Discrete Input Registers (only keep warning)
#(single-bit; read-only)
DiscreteInput {
  mode: []
  warning: []
}
#Coil Registers
#(single-bit; read/write)
Coil {
  reg: []
}
