#MODBUS Floating Point Input Registers
ID="CWMS"
description="CWMS 分析儀"

protocol=["serial", "tcp"]
# multiplier=1.0

#check DataType 8
byteSwapMode=9
byteSwapMode64=15

# ["測項代碼", 位址]
Data: [  
  ["COLOR", 2000]
  ["FLOW_IN", 2002]
  ["FLOW_OUT", 2004]
  ["COD", 5000]    
  ["PH", 5004]
  ["TSS", 5008]
  ["TEMP", 5012]
  ["NH4", 5016]  
]
# zero address, span address
Calibration: []

#(32-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input {
  reg: [
  ]
}
#(64-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input64 {
  reg: [
  ]
}
#(32-bit IEEE 754 format; read/write in high-word, low-word order; read/write)
Holding {
  reg: [       
    [2000, "Color", "Pt-Co"]
	[2002, "Flow In", "m3/h"]        
	[2004, "Flow_OUT", "m3/h"]
  ]
}

Holding64 {
  reg: [
  	[5000, "COD", ""]
	[5004, "pH", ""]  
	[5008, "TSS", "mg/l"]	
	[5012, "Temp", "C"]    
	[5016, "NH4+", ""]	
  ]
}

#Discrete Input Registers (only keep warning)
#(single-bit; read-only)
DiscreteInput {
  mode: []
  warning: []
}
#Coil Registers
#(single-bit; read/write)
Coil {
  reg: []
}
