#MODBUS Floating Point Input Registers
ID="FakeDo"
description="Fake Do"

# protocol=["serial", "tcp"]
# multiplier=1.0

#check DataType 8
#byteSwapMode=8
#byteSwapMode64=14/15

# ["測項代碼", 位址]
Data: [
]
# zero address, span address
Calibration: [0, 0]

#(32-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input {
  reg: [
  ]
}

#(64-bit IEEE 754 format; read in high-word, low-word order; read-only)
Input64 {
  reg: [
  ]
}

#(32-bit IEEE 754 format; read/write in high-word, low-word order; read/write)
Holding {
  reg: [
  ]
}

Holding64 {
  reg: [
  ]
}
#Discrete Input Registers (only keep warning)
#(single-bit; read-only)
DiscreteInput {
  mode: [
  ]
  warning: [
  ]
}

#If IsDoDevice is true, Coil will support WriteDo message
DoDevice = true

#Coil Registers
#(single-bit; read/write)
Coil {
  reg: [
    [0, "DO 1"]
    [1, "DO 2"]
    [2, "DO 3"]
    [3, "DO 4"]
  ]
}
